### ISSUE TITLE
Tool Fails to run - Errors to do with Columns

### ISSUE THREAD

**Issue by MikeHayward** [EsriUK/OSMM-Styling#3]
I am using Arc GIS 10.4 and my data is OS Mastermap Topography Layer Shapefiles from the EA Partner Data Catalogue, which appears to be very up-to-date (more recent than October 2016).

My issue is the tool fails on Column errors when I try to add Style Columns. I have not tried removing Columns as I have none to remove.

For each OS tile I am using, there are 6 shapefiles and these cover the range of formats (point, line, polygon, text). The fields are slightly different in each table, shown in the spreadsheet, and I wonder if this is the root of the issue?
[Table of Shapefile Fields.xlsx](https://github.com/EsriUK/OSMM-Styling/files/814039/Table.of.Shapefile.Fields.xlsx)

The inputs were the file geodatabase containing all the shapefiles as feature classes for the Workspace (blanked out some bits of the file location), 'SX' as the TablePrefix & 'Add Style' for ToolMode.
![osmm tool window](https://cloud.githubusercontent.com/assets/26141569/23511175/3456fc8c-ff54-11e6-9eb4-5049832db5c8.PNG)

Below is the text for the tool run dialog:
![tool failure window](https://cloud.githubusercontent.com/assets/26141569/23511269/7498fb38-ff54-11e6-9792-dbdb3121cdf1.PNG)

Executing: OSMMStyleTool "P:\        \MNS\Projects\        \20170228 - OS Mastermap Topography\EADATASHARE_OI1096462\OI1096462\data\SX\SX7555_boundaryline_part" SX "Add Style"
Start Time: Thu Mar 02 13:57:07 2017
Running script OSMMStyleTool...
Opening GDB
Adding style columns
Error adding columns: "SXAnno" does not exist
Failed script OSMMStyleTool...

Traceback (most recent call last):
  File "S:\GIS\Tools\ArcMap\OSMM-Styling-master\OSMM-Styling-master\StyleScripts\style_tool.py", line 244, in <module>
    main()
  File "S:\GIS\Tools\ArcMap\OSMM-Styling-master\OSMM-Styling-master\StyleScripts\style_tool.py", line 55, in main
    AddStyles(tablePrefix)
  File "S:\GIS\Tools\ArcMap\OSMM-Styling-master\OSMM-Styling-master\StyleScripts\style_tool.py", line 101, in AddStyles
    with arcpy.da.UpdateCursor(tablePrefix +"Line", fields) as cur:
RuntimeError: cannot open 'SXLine'

Failed to execute (OSMMStyleTool).
Failed at Thu Mar 02 13:57:17 2017 (Elapsed Time: 9.37 seconds)

**Comment by MikeHayward** [comment]
Thanks Peter,

Just for completeness for other users in my shoes, here was my scenario and how I got the tool to work after several days!

I cannot be certain but I believe my problems are due to incorrect field names in the supplied data from our client (desgroup and desterm instead of descgroup and descterm). Unfortunately, to work this out I had to dissect the scripts and layer files to establish the expected field names.

Contracted field names (probably due to .shp file data supplied) such as "txstring", "orientat" and "anchpos" were also present and needed to be mapped to fields with the correct full names (orientation, textstring, anchorposition); similarly rotation data for annotations had been multiplied by 10 - I assume due to issues of dealing with a decimal point.

2 things to note:
-  The tool does not work properly with shapefiles as field names >10 are required (most important for Cartographic Text) so you will need to work from geodatabases.
- The layer files from ESRI expect the field "colour_code" but the American spelling is used in the tool scripting "color_code"
