### ISSUE TITLE
Tool fails if no objects in any of the expected feature classes

### ISSUE THREAD

**Issue by ianholmes** [EsriUK/OSMM-Styling#6]
This tool fails if there are no objects in any of the feature classes it is expecting with the error:

```
Updating table: Schema9bnd
Updated 0 rows in table: Schema9bnd
Failed script OSMMStyleTool...

Traceback (most recent call last):
  File "C:\Git\OSMM-Styling\StyleScripts\style_tool.py", line 244, in <module>
    main()
  File "C:\Git\OSMM-Styling\StyleScripts\style_tool.py", line 55, in main
    AddStyles(tablePrefix)
  File "C:\Git\OSMM-Styling\StyleScripts\style_tool.py", line 185, in AddStyles
    del cur, row
UnboundLocalError: local variable 'row' referenced before assignment

Failed to execute (OSMMStyleTool).
```
![image](https://user-images.githubusercontent.com/9719724/42038528-17066792-7ae3-11e8-8b62-357f5d05d704.png)

**Comment by ianholmes** [comment]
I'm not sure my above statement is actually correct, I remedied this error by changing 'bnd' to 'Bnd' in the style_tool.py file. So it seems to be a case mismatch but I can't figure out why others with a case mismatch work fine (e.g. 'anno' works even though the feature class is called 'Anno').
